services:
  app:
    build:
      context: './backend'
      dockerfile: Dockerfile
    container_name: backend_GP
    ports:
      - "8080:8080"
    depends_on:
      - mysql
#      - mongo
    networks:
      - backend
    volumes:
      - ./backend/src:/backend/src        # Mount source code for live reload
      - ./backend/target:/backend/target  # Mount target directory for output
      - ~/.m2:/root/.m2                 # Cache Maven dependencies
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for Docker-in-Docker access

  frontend:
    build:
      context: './front'
      dockerfile: Dockerfile
    container_name: frontend_GP
    ports:
      - "3000:3000"
    depends_on:
      - app
    networks:
      - backend
    volumes:
      - ./front/src:/app/src                 # Mount frontend code for live reload

  ml_model:
    build:
      context: './MLModel'
      dockerfile: Dockerfile
    container_name: MLModel_GP
    ports:
      - "5000:5000"
    networks:
      - backend
    volumes:
      - ./MLModel:/app                # Mount ML model code

  mysql:
    image: mysql:8.0
    container_name: mysql_GP
    restart: always
    environment:
      MYSQL_DATABASE: mysql_GP
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_GP
    environment:
      PMA_HOST: mysql_GP
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8082:80"
    networks:
      - backend
    depends_on:
      - mysql

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
    driver: local