version: "3.8"

services:
  backend:
    image: abdayman/backendids:latest
    container_name: backend_GP
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker-in-Docker access

  frontend:
    image: abdayman/frontendids:latest
    container_name: frontend_GP
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - backend

  ml_model:
    image: abdayman/mlmodel:latest
    container_name: MLModel_GP
    ports:
      - "5000:5000"
    networks:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql_GP
    restart: always
    environment:
      MYSQL_DATABASE: mysql_GP
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_GP
    environment:
      PMA_HOST: mysql_GP
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8082:80"
    networks:
      - backend
    depends_on:
      - mysql

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
    driver: local
