
services:

  mysql:
    image: mysql:latest
    container_name: mysql_GP
    restart: always
    environment:
      MYSQL_DATABASE: mysql_GP
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dockerdeployment_mysql_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
     interval: 10s
     timeout: 5s
     retries: 5


  backend:
    image: abdayman/backendids:latest
    container_name: backend_ids
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker-in-Docker access

  frontend:
    image: abdayman/frontendids:latest
    container_name: frontend_ids
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - backend

  ml_model:
    image: abdayman/mlmodel:latest
    container_name: MLModel_ids
    ports:
      - "5000:5000"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  dockerdeployment_mysql_data:
    driver: local
