package java.backend.service.authService;

public enum AuthConstants {
    INVALID_CREDENTIALS,
    USER_NOT_FOUND,
    WRONG_PASSWORD,
    SESSION_EXPIRED,
    USER_ALREADY_EXISTS,
    USER_NOT_ACTIVE,
    USER_ALREADY_REGISTERED,
    EMAIL_ALREADY_EXISTS,
    USER_NOT_VERIFIED,
    USER_ALREADY_BLOCKED,
    USER_ROLE_NOT_ALLOWED,
    USER_EMAIL_NOT_VERIFIED,
    USER_EMAIL_ALREADY_EXISTS,
    USER_PASSWORD_NOT_COMPLEX,
    USER_EMAIL_NOT_CONFIRMED,
    USER_EMAIL_ALREADY_CONFIRMED,
    AUTH_FAILED
}
