name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    steps:
      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.AWS_EC2_KEY }} ubuntu@${{ secrets.AWS_EC2_IP }} 'docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest && docker-compose up -d'
      - name: SSH into Frontend EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_FRONTEND_HOST }}
          username: i-013c7f2dc6a0b6e68
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # Pull the latest frontend image
            docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest

            # Stop and remove existing frontend container
            docker stop frontend || true
            docker rm frontend || true

            # Run the frontend container
            docker run -d -p 3000:3000 --name frontend ${{ secrets.DOCKER_USERNAME }}/frontend:latest