name: MLModel CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mlmodel:latest ./MLModel

      # Step 5: Push the Docker image to DockerHub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mlmodel:latest

      # Step 6: Deploy the Docker container
      - name: Deploy MLModel
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/mlmodel:latest
          docker stop MLModel_GP || true
          docker rm MLModel_GP || true
          docker run -d --name MLModel_GP -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/mlmodel:latest
